TimeBasedPictures: BoostColor Class Reference
BoostColor Class Reference
#include <boostColor.hpp>
Public Member Functions
BoostColor (std::shared_ptr< Base > mother, int id, float threshhold, int modi, std::shared_ptr< std::vector< float >> color, int offset, int stride)
~BoostColor () override
int getTypenumber () override
int get_calculation_specification () override
void calc (int id, int start, int length, int sign, cv::Mat &result, float &factor, cv::Mat &fac_mat) override
void compute_frame (cv::Mat &result, cv::Mat &fac_mat, cv::Mat &current_frame, int sign)
void manipulate (float threshhold, int modi, std::shared_ptr< std::vector< float >> colors, int offset, int stride)
Public Member Functions inherited from Transformation
Transformation (std::shared_ptr< Base > mother, int id, int offset, int stride)
int get_id ()
int get_offset ()
int get_stride ()
virtual ~Transformation ()
int get_upload_specification ()
virtual void add_connection (int id, Segment *segment)
void delete_connection (int id)
void update_connections ()
void trigger_connections ()
Private Attributes
float m_threshhold
int m_ptr_delta
int m_modi
cv::Point m_pnt_min
cv::Point m_pnt_max
std::shared_ptr< std::vector< float > > m_colors
Additional Inherited Members
Protected Attributes inherited from Transformation
int m_offset
int m_stride
std::shared_ptr< cv::VideoCapture > m_video
int m_img_type
int m_id
int m_type
int m_upload_specification
int m_calc_specification
bool m_recompute = false
std::mutex m_mutex_connections
std::shared_ptr< Base > m_base
std::map< int, Segment *> m_all_connections = std::map< int, Segment* >()
Detailed Description
Definition at line 14 of file boostColor.hpp.
Constructor & Destructor Documentation
BoostColor()
BoostColor::BoostColor (std::shared_ptr< Base > mother, int id, float threshhold, int modi, std::shared_ptr< std::vector< float >> color, int offset, int stride)
Definition at line 17 of file boostColor.cpp.
References Transformation::m_calc_specification, m_colors, m_modi, m_pnt_max, m_pnt_min, m_ptr_delta, m_threshhold, Transformation::m_type, and Transformation::m_upload_specification.
~BoostColor()
BoostColor::~BoostColor () override
Definition at line 32 of file boostColor.cpp.
Member Function Documentation
getTypenumber()
int BoostColor::getTypenumber () override virtual
Implements Transformation.
Definition at line 36 of file boostColor.cpp.
References Transformation::m_type.
get_calculation_specification()
int BoostColor::get_calculation_specification () override virtual
Implements Transformation.
Definition at line 40 of file boostColor.cpp.
References Transformation::m_calc_specification.
calc()
void BoostColor::calc (int id, int start, int length, int sign, cv::Mat & result, float & factor, cv::Mat & fac_mat) override virtual
Implements Transformation.
Definition at line 44 of file boostColor.cpp.
References compute_frame(), Transformation::m_img_type, Transformation::m_offset, Transformation::m_stride, and Transformation::m_video.
compute_frame()
void BoostColor::compute_frame (cv::Mat & result, cv::Mat & fac_mat, cv::Mat & current_frame, int sign)
Definition at line 71 of file boostColor.cpp.
References utils::CIE76(), utils::CIE94(), utils::dE2000(), m_colors, m_modi, m_pnt_max, m_pnt_min, m_ptr_delta, m_threshhold, and utils::rgb2lab().
Referenced by calc().
manipulate()
void BoostColor::manipulate (float threshhold, int modi, std::shared_ptr< std::vector< float >> colors, int offset, int stride)
Definition at line 154 of file boostColor.cpp.
References m_colors, m_modi, Transformation::m_offset, Transformation::m_stride, m_threshhold, and Transformation::update_connections().
Referenced by Base::manipulate_transformation().
Member Data Documentation
m_threshhold
float BoostColor::m_threshhold private
Definition at line 25 of file boostColor.hpp.
Referenced by BoostColor(), compute_frame(), and manipulate().
m_ptr_delta
int BoostColor::m_ptr_delta private
Definition at line 26 of file boostColor.hpp.
Referenced by BoostColor(), and compute_frame().
m_modi
int BoostColor::m_modi private
Definition at line 27 of file boostColor.hpp.
Referenced by BoostColor(), compute_frame(), and manipulate().
m_pnt_min
cv::Point BoostColor::m_pnt_min private
Definition at line 28 of file boostColor.hpp.
Referenced by BoostColor(), and compute_frame().
m_pnt_max
cv::Point BoostColor::m_pnt_max private
Definition at line 29 of file boostColor.hpp.
Referenced by BoostColor(), and compute_frame().
m_colors
std::shared_ptr<std::vector<float> > BoostColor::m_colors private
Definition at line 30 of file boostColor.hpp.
Referenced by BoostColor(), compute_frame(), and manipulate().
The documentation for this class was generated from the following files:
backend/TBPsys/include/boostColor.hpp
backend/TBPsys/src/boostColor.cpp