TimeBasedPictures: Overplott Class Reference
Overplott Class Reference
#include <overplott.hpp>
Public Member Functions
Overplott (std::shared_ptr< Base > mother, int id, cv::Mat ref, float threshhold, int modi, int offset, int stride)
~Overplott () override
int getTypenumber () override
int get_calculation_specification () override
void calc (int id, int start, int length, int sign, cv::Mat &result, float &factor, cv::Mat &fac_mat) override
void compute_frame (cv::Mat &result, cv::Mat &fac_mat, cv::Mat &current_frame)
void manipulate (cv::Mat ref_frame, float threshhold, int modi, int offset, int stride)
void late_merge (cv::Mat &result, cv::Mat &facs, cv::Mat &tmp_result)
Public Member Functions inherited from Interpretation
Interpretation (std::shared_ptr< Base > mother, int id, int offset, int stride)
int get_id ()
int get_offset ()
int get_stride ()
virtual ~Interpretation ()
int get_upload_specification ()
virtual void add_connection (int id, Segment *segment)
void delete_connection (int id)
void update_connections ()
void trigger_connections ()
Private Attributes
float m_threshhold
int m_ptr_delta
int m_modi
cv::Point m_pnt_min
cv::Point m_pnt_max
cv::Mat m_reference
Additional Inherited Members
Protected Attributes inherited from Interpretation
int m_offset
int m_stride
std::shared_ptr< cv::VideoCapture > m_video
int m_img_type
int m_id
int m_type
int m_upload_specification
int m_calc_specification
bool m_recompute = false
std::mutex m_mutex_connections
std::shared_ptr< Base > m_base
std::map< int, Segment *> m_all_connections = std::map< int, Segment* >()
Detailed Description
Definition at line 11 of file overplott.hpp.
Constructor & Destructor Documentation
Overplott()
Overplott::Overplott (std::shared_ptr< Base > mother, int id, cv::Mat ref, float threshhold, int modi, int offset, int stride)
Definition at line 13 of file overplott.cpp.
References Interpretation::m_calc_specification, m_modi, m_pnt_max, m_pnt_min, m_ptr_delta, m_reference, m_threshhold, Interpretation::m_type, and Interpretation::m_upload_specification.
                                                                                                                        :
 Interpretation{ mother, id,  offset, stride},
 m_reference{ref},
 m_threshhold{threshhold},
 m_modi{modi},
 m_ptr_delta{mother->get_img_delta()},
 m_pnt_min{mother->get_min_Point()},
 m_pnt_max{mother->get_max_Point()}
 {
   m_type                  = 2;  //overplott
   m_calc_specification    = 1;  //extending
   m_upload_specification  = 1;  //with fac mat
 }
~Overplott()
Overplott::~Overplott () override
Definition at line 27 of file overplott.cpp.
                      {
   //std::cout<<"deleting interpretation-boost\n";
 }
Member Function Documentation
getTypenumber()
int Overplott::getTypenumber () override virtual
Implements Interpretation.
Definition at line 31 of file overplott.cpp.
References Interpretation::m_type.
{
   return m_type;
 }
get_calculation_specification()
int Overplott::get_calculation_specification () override virtual
Implements Interpretation.
Definition at line 35 of file overplott.cpp.
References Interpretation::m_calc_specification.
{
   return m_calc_specification; //standard sum-game
 }
calc()
void Overplott::calc (int id, int start, int length, int sign, cv::Mat & result, float & factor, cv::Mat & fac_mat) override virtual
Implements Interpretation.
Definition at line 39 of file overplott.cpp.
References compute_frame(), late_merge(), Interpretation::m_img_type, Interpretation::m_offset, m_pnt_max, Interpretation::m_stride, and Interpretation::m_video.
{
   auto start_time = std::chrono::high_resolution_clock::now();
   cv::Mat tmp_frame;
   m_video->set( CV_CAP_PROP_POS_MSEC, start/*frameTime*/);
   if(sign > 0)
   {
     for(int i = 0; i < length; i++){
       if(start + i < m_offset || (start - m_offset + i) % (m_stride + 1) != 0 ){
         m_video->grab();
       }
       else{
         m_video->read(tmp_frame);
         if(tmp_frame.empty()){
           std::cout << "frame not loaded. \n";
         }
         tmp_frame.convertTo(tmp_frame, m_img_type);   //do this for the whole video right at the start!?
         compute_frame(result, fac_mat, tmp_frame);
       }
       auto end_time = std::chrono::high_resolution_clock::now();
       auto duration = std::chrono::duration_cast< std::chrono::milliseconds >( end_time - start_time ).count();
       #ifdef show_time
           std::cout << "\t\t + Boost ("<<length<<") time: \t" << duration << std::endl;
       #endif
     }
   }
   else{
     //late merge
     cv::Mat tmp_result = cv::Mat(m_pnt_max.y, m_pnt_max.x, m_img_type, cv::Scalar(0,0,0));
     for(int i = 0; i < length; i++){
       if(start + i < m_offset || (start - m_offset + i) % (m_stride + 1) != 0 ){
         m_video->grab();
       }
       else{
         m_video->read(tmp_frame);
         if(tmp_frame.empty()){
           std::cout << "frame not loaded. \n";
         }
         tmp_frame.convertTo(tmp_frame, m_img_type);   //do this for the whole video right at the start!?
         compute_frame(tmp_result, fac_mat, tmp_frame);
       }
     }
     late_merge(result, fac_mat, tmp_result);
   }
   auto end_time = std::chrono::high_resolution_clock::now();
   auto duration = std::chrono::duration_cast< std::chrono::milliseconds >( end_time - start_time ).count();
   #ifdef show_time
       std::cout << "\t\t + Boost ("<<length<<") time: \t" << duration << std::endl;
   #endif
 }
compute_frame()
void Overplott::compute_frame (cv::Mat & result, cv::Mat & fac_mat, cv::Mat & current_frame)
Definition at line 92 of file overplott.cpp.
References utils::CIE76(), utils::CIE94(), utils::dE2000(), m_modi, m_pnt_max, m_pnt_min, m_ptr_delta, m_reference, m_threshhold, and utils::rgb2lab().
Referenced by calc().
{
   // if(m_modi == 0){
   //   cv::Mat mask;
   //   cv::absdiff(current_frame, m_reference, mask);
   //   mask = (mask > m_threshhold);
   //   mask.convertTo(mask, CV_32FC3);
   //   int from_to[] = { 0,0, 0,1, 0,2};
   //   cv::mixChannels(&mask, 1, &mask, 1, from_to, 3);
   //   result = current_frame.mul(mask) * (float) ((float)1 / ((float)255));
   //   fac_mat = mask * (float) ((float)1 / ((float)255));
   // }
   // else if(m_modi == 1){
   //   cv::Mat mask;
   //   cv::Mat grey_ref = m_reference.clone();
   //   cv::Mat grey_current = current_frame.clone();
   //   cv::Mat tmp = cv::Mat(m_base->get_height(), m_base->get_width(), m_base->get_img_type(), cv::Scalar(0,0,0));
   //
   //   cv::cvtColor(current_frame, grey_current, CV_BGR2GRAY);
   //   cv::cvtColor(m_reference, grey_ref, CV_BGR2GRAY);
   //   grey_current.convertTo(grey_current, CV_32FC3);
   //   grey_ref.convertTo(grey_ref, CV_32FC3);
   //
   //   cv::absdiff(grey_current, grey_ref, mask);
   //   mask = (mask > m_threshhold);
   //   mask.convertTo(mask, CV_32FC3);
   //
   //   int from_to[] = { 0,0, 0,1, 0,2};
   //   cv::mixChannels(&mask, 1, &tmp, 1, from_to, 3);
   //   result = current_frame.mul(tmp) * (float) ((float)1 / ((float)255));
   //   fac_mat = tmp * (float) ((float)1 / ((float)255));
   // }
   //else if(m_modi == 0 || m_modi == 1 || m_modi == 2 || m_modi == 3 || m_modi == 4){
     for (unsigned int row = m_pnt_min.y; row < m_pnt_max.y; ++row) {
       //ptr:
       float* ptr_res            =  (float*) result.ptr(row);
       float* ptr_fac            =  (float*) fac_mat.ptr(row);
       const float* ptr_ref      =  (float*) m_reference.ptr(row);
       const float* ptr_current  =  (float*) current_frame.ptr(row);
       for (unsigned int col = m_pnt_min.x; col < m_pnt_max.x; col++) {
         //ptr:
         float *uc_pixel_res           = ptr_res;
         float *uc_pixel_fac           = ptr_fac;
         const float *uc_pixel_ref     = ptr_ref;
         const float *uc_pixel_current = ptr_current;
         //current frame != ref frame -> result frame/ result fac
         // float distance_RGB = sqrt(pow(uc_pixel_ref[0] - uc_pixel_current[0], 2) +
         //                           pow(uc_pixel_ref[1] - uc_pixel_current[1], 2) +
         //                           pow(uc_pixel_ref[2] - uc_pixel_current[2], 2));
         float distance_RGB = -1;
         cv::Scalar ref = utils::rgb2lab(uc_pixel_ref[0], uc_pixel_ref[1], uc_pixel_ref[2]);
         cv::Scalar current = utils::rgb2lab(uc_pixel_current[0], uc_pixel_current[1], uc_pixel_current[2]);
         if(m_modi == 0){
           distance_RGB = sqrt(pow(uc_pixel_ref[0] - uc_pixel_current[0], 2) +
                                      pow(uc_pixel_ref[1] - uc_pixel_current[1], 2) +
                                      pow(uc_pixel_ref[2] - uc_pixel_current[2], 2));
         }else if(m_modi == 1){
           distance_RGB = abs(((uc_pixel_ref[0]+uc_pixel_ref[1] + uc_pixel_ref[2])/3)-((uc_pixel_current[0]+uc_pixel_current[1] + uc_pixel_current[2])/3));
         }else if(m_modi == 2){
           distance_RGB = utils::dE2000(ref, current, 0.1f, 100.0f, 100.0f);
         }
         else if(m_modi == 3){
           distance_RGB = utils::CIE76(ref, current, 1.0f, 0.0f, 0.0f);
         }
         else if(m_modi == 4){
           distance_RGB = utils::CIE94(ref, current, 5.0f, 100.0f, 100.0f);
         }
         //std::cout<<" distance: "<<distance_RGB <<"\n";
         if(distance_RGB > m_threshhold){
             uc_pixel_res[0] = uc_pixel_current[0];
             uc_pixel_res[1] = uc_pixel_current[1];
             uc_pixel_res[2] = uc_pixel_current[2];
             uc_pixel_fac[0] = 1;
             uc_pixel_fac[1] = 1;
             uc_pixel_fac[2] = 1;
         }
         //shift ptr:
         ptr_res     += m_ptr_delta;
         ptr_current += m_ptr_delta;
         ptr_ref     += m_ptr_delta;
         ptr_fac     += m_ptr_delta;
       }
     }
 }
manipulate()
void Overplott::manipulate (cv::Mat ref_frame, float threshhold, int modi, int offset, int stride)
Definition at line 197 of file overplott.cpp.
References m_modi, Interpretation::m_offset, m_reference, Interpretation::m_stride, m_threshhold, and Interpretation::update_connections().
Referenced by Base::manipulate_interpretation().
{
   bool update_status = false;
   cv::Mat tmp;
   double min = 0, max = 0;
   cv::absdiff(m_reference, ref_frame, tmp);
   cv::minMaxLoc(tmp, &min, &max);
   if(max > 0){
     m_reference = ref_frame;
     update_status = true;
   }
   if(m_threshhold != threshhold){
     m_threshhold = threshhold;
     update_status = true;
   }
   if(m_modi != modi){
     m_modi = modi;
     update_status = true;
   }
   if(offset != m_offset){
     m_offset = offset;
     update_status = true;
   }
   if(stride != m_stride){
     m_stride = stride;
     update_status = true;
   }
   if(update_status){
     update_connections();
   }
 }
late_merge()
void Overplott::late_merge (cv::Mat & result, cv::Mat & facs, cv::Mat & tmp_result)
Definition at line 184 of file overplott.cpp.
Referenced by calc().
{
   cv::Mat mask;
   mask = (result == 0);
   mask.convertTo(mask, CV_32FC3);
   result      += tmp_result.mul(mask)/(float)255;
   tmp_result   = (tmp_result > 0);
   tmp_result.convertTo(tmp_result, CV_32FC3);
   int from_to[] = { 0,0, 0,1, 0,2};
   cv::mixChannels(&tmp_result, 1, &tmp_result, 1, from_to, 3);
   facs        += mask.mul(tmp_result)/(float)255;
 }
Member Data Documentation
m_threshhold
float Overplott::m_threshhold private
Definition at line 23 of file overplott.hpp.
Referenced by compute_frame(), manipulate(), and Overplott().
m_ptr_delta
int Overplott::m_ptr_delta private
Definition at line 24 of file overplott.hpp.
Referenced by compute_frame(), and Overplott().
m_modi
int Overplott::m_modi private
Definition at line 25 of file overplott.hpp.
Referenced by compute_frame(), manipulate(), and Overplott().
m_pnt_min
cv::Point Overplott::m_pnt_min private
Definition at line 26 of file overplott.hpp.
Referenced by compute_frame(), and Overplott().
m_pnt_max
cv::Point Overplott::m_pnt_max private
Definition at line 27 of file overplott.hpp.
Referenced by calc(), compute_frame(), and Overplott().
m_reference
cv::Mat Overplott::m_reference private
Definition at line 28 of file overplott.hpp.
Referenced by compute_frame(), manipulate(), and Overplott().
The documentation for this class was generated from the following files:
backend/TBPsys/include/overplott.hpp
backend/TBPsys/src/overplott.cpp