TimeBasedPictures: Segment Class Reference
Segment Class Reference
#include <segment.hpp>
Public Member Functions
Segment (int start_frame, int last_frame, double intensity_local, double intensity_gloabl, std::shared_ptr< Base > mother, int id)
~Segment ()
bool work (int &work_size)
bool interpret_free (int &work_size)
bool interpret_extending (int &work_size)
bool interpret_one_way (int &work_size)
bool interpret_directed (int &work_size)
void update_intensity ()
void updateMask (std::string mask_path)
void revert_influence ()
void upload_influence ()
void move_in_time (int delta)
void set_exposure (int new_exposure)
void set_startframe (int imgs)
void set_endframe (int imgs)
void set_exposure_delta (int delta)
void set_local_intensity (float i)
void set_global_intensity (float i)
void manipulate (int start, int end, float local_i, float global_i, bool hasMask)
void set_interpretation (std::shared_ptr< Interpretation > interpret)
void update_interpretation ()
void trigger_interpretation ()
void delete_seg ()
void reset ()
void soft_reset ()
float get_progress ()
int get_start ()
int get_end ()
Private Member Functions
void ready_to_work ()
void save_segment_out ()
void normalize_factor (cv::Mat &influence, cv::Mat &factors)
Private Attributes
int m_id
float m_percent
bool m_work_done
bool m_hasMask_destin
bool m_hasMask_actual
int m_frame_start_destin
int m_frame_last_destin
int m_frame_start_actual
int m_frame_last_actual
float m_intensity_local_destin
float m_intensity_global_destin
float m_intensity_local_actual
float m_intensity_global_actual
std::shared_ptr< Interpretation > m_interpretation
std::shared_ptr< Interpretation > m_new_interpretation
cv::Mat m_values_abs
cv::Mat m_values_fac
cv::Mat m_mask
float m_uni_fac
std::shared_ptr< Base > m_mother
std::mutex m_mutex_soll
std::mutex m_mutex_state
bool m_needs_reset
bool m_needs_soft_reset
Detailed Description
Definition at line 29 of file segment.hpp.
Constructor & Destructor Documentation
Segment()
Segment::Segment (int start_frame, int last_frame, double intensity_local, double intensity_gloabl, std::shared_ptr< Base > mother, int id)
Definition at line 11 of file segment.cpp.
References m_frame_last_actual, m_frame_last_destin, m_frame_start_actual, m_frame_start_destin, m_hasMask_actual, m_hasMask_destin, m_id, m_intensity_global_actual, m_intensity_global_destin, m_intensity_local_actual, m_intensity_local_destin, m_interpretation, m_mask, m_mutex_soll, m_mutex_state, m_needs_reset, m_needs_soft_reset, m_new_interpretation, m_percent, m_uni_fac, m_values_abs, m_values_fac, m_work_done, and ready_to_work().
                                                                                                                                     :
   m_mother{mother},
   m_frame_start_destin{start_frame},
   m_frame_last_destin{last_frame},
   m_frame_start_actual{-1},
   m_frame_last_actual{-1},
   m_intensity_local_destin{intensity_local},
   m_intensity_global_destin{intensity_global},
   m_intensity_local_actual{intensity_local},
   m_intensity_global_actual{intensity_global},
   m_values_abs{cv::Mat(mother->get_height(), mother->get_width(), mother->get_img_type(), cv::Scalar(0,0,0))},
   m_values_fac{cv::Mat(mother->get_height(), mother->get_width(), mother->get_img_type(), cv::Scalar(0,0,0))},
   m_mask{cv::Mat(mother->get_height(), mother->get_width(), CV_32FC1, cv::Scalar(0))},
   m_uni_fac{0.0f},
   m_interpretation{std::make_shared<Average>(mother, -1, 0, 0)},
   m_mutex_soll{},
   m_mutex_state{},
   m_percent{0.0f},
   m_work_done{true},
   m_hasMask_actual{false},
   m_hasMask_destin{false},
   m_new_interpretation{NULL},
   m_needs_reset{false},
   m_needs_soft_reset{false},
   m_id{id} {
     m_interpretation->add_connection(id, this);
     ready_to_work();
   }
~Segment()
Segment::~Segment ()
Definition at line 40 of file segment.cpp.
                  {
   std::cout << "delete segment. \n";
 }
Member Function Documentation
work()
bool Segment::work (int & work_size)
Definition at line 177 of file segment.cpp.
References interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), m_frame_last_actual, m_frame_last_destin, m_frame_start_actual, m_frame_start_destin, m_hasMask_actual, m_hasMask_destin, m_id, m_interpretation, m_mutex_soll, m_mutex_state, m_needs_reset, m_needs_soft_reset, m_new_interpretation, m_percent, m_work_done, reset(), revert_influence(), save_segment_out(), soft_reset(), update_intensity(), and upload_influence().
{
   //ist soll gleich ist stand?
   m_mutex_state.lock();
   bool state = m_work_done;
   m_mutex_state.unlock();
   update_intensity();
   m_mutex_soll.lock();
   //set new interpetation:
   if(m_new_interpretation != NULL) {
       revert_influence();
       reset();
       m_interpretation->delete_connection(m_id);
       m_interpretation = m_new_interpretation;
       m_interpretation->add_connection(m_id, this);
       m_new_interpretation = NULL;
   }
   //check wether mask is on/off:
   if(m_hasMask_actual!=m_hasMask_destin)
   {
     revert_influence();
     m_hasMask_actual=m_hasMask_destin;
     upload_influence();
   }
   //interpretation need reset:
   if(m_needs_reset) {
     revert_influence(); //dont know?
     reset();
     m_needs_reset = false;
   }
   if(m_needs_soft_reset) {
     // revert_influence(); //dont know?
     // reset();
     soft_reset();
     m_needs_soft_reset = false;
   }
   m_mutex_soll.unlock();
   if(work_size > 0) {
     if(m_interpretation->get_calculation_specification() == 0){
       state = interpret_free( work_size );
     }
     else if(m_interpretation->get_calculation_specification() == 1){
       state = interpret_extending( work_size );
     }
     else if(m_interpretation->get_calculation_specification() == 2){
       state = interpret_one_way( work_size );
     }
     else if(m_interpretation->get_calculation_specification() == 3){
       state = interpret_directed( work_size );
     }
     else{
       std::cout<<"Other interpretation traversal not implemnted yet. \n";
     }
     m_mutex_soll.lock();
     float soll = m_frame_last_destin - m_frame_start_destin;
     float ist = abs(m_frame_last_actual - m_frame_last_destin) + abs(m_frame_start_actual - m_frame_start_destin);
     float percentage = 100 - 100.0 * ( ist / soll );
     if( percentage < 0 ){
       percentage = 0;
     }
     m_mutex_soll.unlock();
     if(percentage == 100 && state) {
       save_segment_out();
       m_mutex_state.lock();
     }
     else {
       m_mutex_state.lock();
       state = false;
     }
     m_work_done = state;
     m_percent = percentage;
     m_mutex_state.unlock();
   }
   return state;
 }
interpret_free()
bool Segment::interpret_free (int & work_size)
Definition at line 363 of file segment.cpp.
References m_frame_last_actual, m_frame_last_destin, m_frame_start_actual, m_frame_start_destin, m_id, m_interpretation, m_mutex_soll, m_uni_fac, m_values_abs, m_values_fac, reset(), revert_influence(), and upload_influence().
Referenced by work().
{
   m_mutex_soll.lock();
   int dest_start = m_frame_start_destin;
   int dest_end = m_frame_last_destin;
   bool exit_status = false;
   m_mutex_soll.unlock();
   //int delta=m_frame_last_actual-m_frame_start_actual;
   if(m_frame_start_actual > -1) {
     revert_influence();
   }
   cv::Mat tmp_frame;
   cv::Mat tmp_frame_d;
   //shortcuts possible?
   int moves     = abs(dest_start - m_frame_start_actual) + abs(dest_end - m_frame_last_actual);
   int alt_moves = dest_end - dest_start;
   if(alt_moves < moves && m_frame_start_actual>-1) {
     reset();
   }
   //startingpoint:
   if(m_frame_start_actual == -1) {//not yet computed!
     m_frame_start_actual = dest_start;
   }
   if(m_frame_start_actual < dest_start) {
     int length = work_size;
     if(m_frame_start_actual + work_size > dest_start){
       length = dest_start - m_frame_start_actual;
     }
     int sign = -1;
     m_interpretation->calc(m_id, m_frame_start_actual, length, sign, m_values_abs, m_uni_fac, m_values_fac);
     work_size -= length;
     m_frame_start_actual += length;
   }
   else if(m_frame_start_actual > dest_start) {
     int startpoint = m_frame_start_actual - work_size;
     int length = work_size;
     if(startpoint < dest_start) {
       length = m_frame_start_actual - dest_start;
       startpoint = dest_start;
     }
     int sign = 1;
     m_interpretation->calc(m_id, startpoint, length, sign, m_values_abs, m_uni_fac, m_values_fac);
     work_size -= length;
     m_frame_start_actual -= length;
   }
   //endpoint:
   if( work_size > 0 ){
     if(m_frame_last_actual == -1) {//not yet computed!
        m_frame_last_actual = dest_start;
      }
      if(m_frame_last_actual < dest_end) {
        /*ffmpeg:
        double frameRate = m_video.get(CV_CAP_PROP_FPS);
        double frameTime = 1000.0 * m_frame_last_actual / frameRate;
        */
        //m_video.set(CV_CAP_PROP_POS_MSEC, m_frame_last_actual/*frameTime*/);
        int endpoint = m_frame_last_actual + work_size;
        int length = work_size;
        if(endpoint > dest_end){
          endpoint = dest_end;
          length = dest_end - m_frame_last_actual;
        }
        int sign = 1;
        m_interpretation->calc(m_id, m_frame_last_actual, length, sign, m_values_abs, m_uni_fac, m_values_fac);
        work_size -= length;
        m_frame_last_actual += length;
      }
      else if(m_frame_last_actual > dest_end) {
        int startpoint = m_frame_last_actual - work_size;
        int length = work_size;
        if(startpoint < dest_end) {
          length = m_frame_last_actual - dest_end;
          startpoint = dest_end;
        }
        int sign =- 1;
        m_interpretation->calc(m_id, startpoint, length, sign, m_values_abs, m_uni_fac, m_values_fac);
        work_size -= length;
        m_frame_last_actual -= length;
      }
   }
   if(m_frame_start_actual > -1) {
     upload_influence();
   }
   if((dest_start == m_frame_start_actual) && (dest_end == m_frame_last_actual)) {
     exit_status = true;  //ist = soll
   }
   else{
     exit_status = false; //ist != soll
   }
   return exit_status;
 }
interpret_extending()
bool Segment::interpret_extending (int & work_size)
Definition at line 473 of file segment.cpp.
References m_frame_last_actual, m_frame_last_destin, m_frame_start_actual, m_frame_start_destin, m_id, m_interpretation, m_mutex_soll, m_uni_fac, m_values_abs, m_values_fac, reset(), revert_influence(), and upload_influence().
Referenced by work().
{
   //allows only enlargment.. shrinking-> reset
   m_mutex_soll.lock();
   int dest_start = m_frame_start_destin;
   int dest_end = m_frame_last_destin;
   bool exit_status = false;
   m_mutex_soll.unlock();
   //int delta=m_frame_last_actual-m_frame_start_actual;
   if(m_frame_start_actual > -1) {
     revert_influence();
   }
   cv::Mat tmp_frame;
   cv::Mat tmp_frame_d;
   //reset neccessary?
   if( m_frame_last_actual > dest_end )
   {
     reset();
   }else if(m_frame_start_actual < dest_start)
   {
     reset();
   }
   //startingpoint:
   if(m_frame_start_actual == -1) {//not yet computed!
     m_frame_start_actual = dest_start;
   }
   if(m_frame_start_actual < dest_start) {
     std::cout << "a: should not happen !? \n";
   }
   else if(m_frame_start_actual > dest_start) {
     int startpoint = m_frame_start_actual - work_size;
     int length = work_size;
     if(startpoint < dest_start) {
       length = m_frame_start_actual - dest_start;
       startpoint = dest_start;
     }
     int sign = -1;
     // -1 indicates late merge:
     // first calculate overplotting for work length
     // and then insert all pixels to result img & fac, that aren't already used
     m_interpretation->calc(m_id, startpoint, length, sign, m_values_abs, m_uni_fac, m_values_fac);
     work_size -= length;
     m_frame_start_actual -= length;
   }
   //endpoint:
   if( work_size > 0 ){
     if(m_frame_last_actual == -1) {//not yet computed!
        m_frame_last_actual = dest_start;
      }
      if(m_frame_last_actual < dest_end) {
        /*ffmpeg:
        double frameRate = m_video.get(CV_CAP_PROP_FPS);
        double frameTime = 1000.0 * m_frame_last_actual / frameRate;
        */
        //m_video.set(CV_CAP_PROP_POS_MSEC, m_frame_last_actual/*frameTime*/);
        int endpoint = m_frame_last_actual + work_size;
        int length = work_size;
        if(endpoint > dest_end){
          endpoint = dest_end;
          length = dest_end - m_frame_last_actual;
        }
        int sign = 1;
        m_interpretation->calc(m_id, m_frame_last_actual, length, sign, m_values_abs, m_uni_fac, m_values_fac);
        work_size -= length;
        m_frame_last_actual += length;
      }
      else if(m_frame_last_actual > dest_end) {
        std::cout << "b: should not happen !? \n";
      }
   }
   if(m_frame_start_actual > -1) {
     upload_influence();
   }
   if((dest_start == m_frame_start_actual) && (dest_end == m_frame_last_actual)) {
     exit_status = true;  //ist = soll
   }
   else{
     exit_status = false; //ist != soll
   }
   return exit_status;
 }
interpret_one_way()
bool Segment::interpret_one_way (int & work_size)
Definition at line 570 of file segment.cpp.
References m_frame_last_actual, m_frame_last_destin, m_frame_start_actual, m_frame_start_destin, m_id, m_interpretation, m_mutex_soll, m_uni_fac, m_values_abs, m_values_fac, reset(), revert_influence(), and upload_influence().
Referenced by work().
{
 //  std::cout<<"Interpret one way. or another\n";
   //allows only enlargment.. shrinking-> reset
   m_mutex_soll.lock();
   int dest_start = m_frame_start_destin;
   int dest_end = m_frame_last_destin;
   bool exit_status = false;
   m_mutex_soll.unlock();
   //int delta=m_frame_last_actual-m_frame_start_actual;
   if(m_frame_start_actual > -1) {
     revert_influence();
   }
   cv::Mat tmp_frame;
   cv::Mat tmp_frame_d;
   //reset neccessary?
   if( m_frame_last_actual > dest_end )
   {
     reset();
   }
   else if(m_frame_start_actual < dest_start)
   {
     reset();
   }
   else if(m_frame_start_actual > dest_start)
   {
     reset();
   }
   //startingpoint:
   if(m_frame_start_actual == -1) {//not yet computed!
     m_frame_start_actual = dest_start;
   }
   if(m_frame_start_actual < dest_start) {
     std::cout << "a: should not happen !? \n";
   }
   else if(m_frame_start_actual > dest_start) {
         std::cout << "b: should not happen !? \n";
   }
   //endpoint:
   if( work_size > 0 ){
     if(m_frame_last_actual == -1) {//not yet computed!
        m_frame_last_actual = dest_start;
      }
      if(m_frame_last_actual < dest_end) {
        /*ffmpeg:
        double frameRate = m_video.get(CV_CAP_PROP_FPS);
        double frameTime = 1000.0 * m_frame_last_actual / frameRate;
        */
        //m_video.set(CV_CAP_PROP_POS_MSEC, m_frame_last_actual/*frameTime*/);
        int endpoint = m_frame_last_actual + work_size;
        int length = work_size;
        if(endpoint > dest_end){
          endpoint = dest_end;
          length = dest_end - m_frame_last_actual;
        }
        int sign = 1;
        m_interpretation->calc(m_id, m_frame_last_actual, length, sign, m_values_abs, m_uni_fac, m_values_fac);
        work_size -= length;
        m_frame_last_actual += length;
      }
      else if(m_frame_last_actual > dest_end) {
        std::cout << "b: should not happen !? \n";
      }
   }
   if(m_frame_start_actual > -1) {
     upload_influence();
   }
   if((dest_start == m_frame_start_actual) && (dest_end == m_frame_last_actual)) {
     exit_status = true;  //ist = soll
   }
   else{
     exit_status = false; //ist != soll
   }
   return exit_status;
 }
interpret_directed()
bool Segment::interpret_directed (int & work_size)
Definition at line 660 of file segment.cpp.
References Paint::get_time_min(), m_frame_last_actual, m_frame_last_destin, m_frame_start_actual, m_frame_start_destin, m_id, m_interpretation, m_mutex_soll, m_uni_fac, m_values_abs, m_values_fac, Paint::reset_routine(), revert_influence(), soft_reset(), and upload_influence().
Referenced by work().
{
     //allows only enlargment.. shrinking-> reset
     m_mutex_soll.lock();
     int dest_start = m_frame_start_destin;
     int dest_end = m_frame_last_destin;
     bool exit_status = false;
     m_mutex_soll.unlock();
     //int delta=m_frame_last_actual-m_frame_start_actual;
     if(m_frame_start_actual > -1) {
       revert_influence();
     }
     cv::Mat tmp_frame;
     cv::Mat tmp_frame_d;
     //reset neccessary?
     if( m_frame_last_actual > dest_end )
     {
       soft_reset();
     }
     else if(m_frame_start_actual < dest_start)
     {
       soft_reset();
     }
     else if(m_frame_start_actual > dest_start)
     {
       soft_reset();
     }
     //startingpoint:
     if(m_frame_start_actual == -1) {//not yet computed!
       m_frame_start_actual = dest_start;
     }
     //endpoint:
     if( work_size > 0 ){
       if(m_frame_last_actual == -1) {//not yet computed!
          m_frame_last_actual = dest_start;
        }
        Paint& interpretation = dynamic_cast<Paint&>(*m_interpretation);
        interpretation.reset_routine(m_values_abs, m_values_fac, m_id);
        int new_frame = interpretation.get_time_min(m_frame_last_actual,m_id);
        std::cout<<"m_frame_last_actual "<< m_frame_last_actual<<" \n";
        if( new_frame == -1){
          //fully calculated
          m_frame_last_actual = dest_end;
          m_frame_start_actual = dest_start;
        }else if(new_frame < dest_start)
        {
          std::cout<<"warning: in paint defined exposures don't fit to segment: "<<m_id<<" because: "<<new_frame <<" < " <<dest_start<<"\n";
          m_frame_last_actual = dest_end;
          m_frame_start_actual = dest_start;
        }else if(new_frame > dest_end)
        {
          std::cout<<"warning: in paint defined exposures don't fit to segment: "<<m_id<<" because: "<<new_frame <<" > " <<dest_end<<"\n";
          m_frame_last_actual = dest_end;
          m_frame_start_actual = dest_start;
        }
        else{
          //jump to frame desired by interpretation
          m_frame_last_actual = new_frame;
        }
        if(m_frame_last_actual < dest_end) {
          /*ffmpeg:
          double frameRate = m_video.get(CV_CAP_PROP_FPS);
          double frameTime = 1000.0 * m_frame_last_actual / frameRate;
          */
          //m_video.set(CV_CAP_PROP_POS_MSEC, m_frame_last_actual/*frameTime*/);
          int endpoint = m_frame_last_actual + work_size;
          int length = work_size;
          if(endpoint > dest_end){
            endpoint = dest_end;
            length = dest_end - m_frame_last_actual;
          }
          int sign = 1;
          m_interpretation->calc(m_id, m_frame_last_actual, length, sign, m_values_abs, m_uni_fac, m_values_fac);
          work_size -= length;
          m_frame_last_actual += length;
        }
     }
   if(m_frame_start_actual > -1) {
     upload_influence();
   }
   if((dest_start == m_frame_start_actual) && (dest_end == m_frame_last_actual)) {
     exit_status = true;  //ist = soll
   }
   else{
     exit_status = false; //ist != soll
   }
   return exit_status;
 }
update_intensity()
void Segment::update_intensity ()
Definition at line 307 of file segment.cpp.
References m_intensity_global_actual, m_intensity_global_destin, m_intensity_local_actual, m_intensity_local_destin, m_mutex_soll, revert_influence(), and upload_influence().
Referenced by work().
{
     m_mutex_soll.lock();
     float dest_intensity_local = m_intensity_local_destin;
     float dest_intensity_global = m_intensity_global_destin;
     m_mutex_soll.unlock();
     //int delta=m_frame_last_actual-m_frame_start_actual;
     if(m_intensity_local_actual != dest_intensity_local) {
         revert_influence();
         m_intensity_local_actual = dest_intensity_local;
         upload_influence();
     }
     if(m_intensity_global_actual != dest_intensity_global) {
       revert_influence();
       m_intensity_global_actual = dest_intensity_global;
       upload_influence();
     }
 }
updateMask()
void Segment::updateMask (std::string mask_path)
Definition at line 327 of file segment.cpp.
References m_hasMask_actual, m_mask, and m_mother.
Referenced by upload_influence().
{
   if(m_hasMask_actual){
     auto start_time = std::chrono::high_resolution_clock::now();
     cv::Mat new_mask = cv::imread("./" + mask_path);
     if(new_mask.empty()){
       new_mask = cv::Mat(m_mother->get_max_Point().y, m_mother->get_max_Point().x, CV_32FC1, cv::Scalar(0));
       std::cout << "reference image not loaded. Loading empty Image\n";
     }
     else{
       std::cout<<"read nes mask right now\n";
       cv::cvtColor(new_mask, new_mask, CV_BGR2GRAY);
       new_mask.convertTo(new_mask, CV_32FC1);
     }
     cv::Mat tmp_mat_diff_check;
     double min = 0, max = 0;
     cv::absdiff(m_mask, new_mask, tmp_mat_diff_check);
     cv::minMaxLoc(tmp_mat_diff_check, &min, &max);
     if(max > 0){
       std::cout<<"prep to read\n";
       cv::imwrite("oldmask.png", m_mask);
       cv::imwrite("newmask.png", new_mask);
       m_mask = new_mask;
       //cv::absdiff(m_mask, new_mask, m_mask);
     }
     m_mask = m_mask / 255;
     auto end_time = std::chrono::high_resolution_clock::now();
     auto duration = std::chrono::duration_cast< std::chrono::milliseconds >( end_time - start_time ).count();
         std::cout << "\t\t + Seg update Mask: \t" << duration << std::endl;
   }
 }
revert_influence()
void Segment::revert_influence ()
Definition at line 75 of file segment.cpp.
References m_hasMask_actual, m_intensity_global_actual, m_intensity_local_actual, m_interpretation, m_mask, m_mother, m_uni_fac, m_values_abs, m_values_fac, and normalize_factor().
Referenced by interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), update_intensity(), and work().
{
   //std::cout<<"revert\n";
   //should be muted from higher levl
   float intensity = -1;
   bool skip = false;
   cv::Mat factors = m_values_fac.clone();
   cv::Mat influence = m_values_abs.clone();
   if( m_interpretation->getTypenumber() == 0 || m_interpretation->getTypenumber() == 1 || m_interpretation->getTypenumber() == 8){
     if(m_uni_fac != 0)
       influence = (m_values_abs * ((float) 1 / ((float) m_uni_fac))) * m_intensity_local_actual * m_intensity_global_actual;
     else
       skip = true;
     intensity = m_intensity_global_actual;
   }
   else if(m_interpretation->getTypenumber() == 2 || m_interpretation->getTypenumber() == 3 || m_interpretation->getTypenumber() == 4 || m_interpretation->getTypenumber() == 5 || m_interpretation->getTypenumber() == 6  || m_interpretation->getTypenumber() == 7 || m_interpretation->getTypenumber() == 9){
     normalize_factor(influence, factors);
     influence = influence * m_intensity_local_actual * m_intensity_global_actual;
     factors = factors * m_intensity_global_actual;
     intensity = m_uni_fac;
   }
   else{
     std::cout<< "revert influence is not allowed yet " << m_interpretation->getTypenumber() << "\n";
   }
   if(m_hasMask_actual){
     std::cout<<"XXXXXXXXXXrevert influence of mask\n";
     cv::Mat tmp_mask = cv::Mat(m_mother->get_max_Point().y, m_mother->get_max_Point().x, CV_32FC3, cv::Scalar(0,0,0));
     int from_to[] = { 0,0, 0,1, 0,2};
     cv::mixChannels(&m_mask, 1, &tmp_mask, 1, from_to, 3);
     factors = factors.mul(tmp_mask);
     influence = influence.mul(tmp_mask);
     if( m_interpretation->getTypenumber() == 0 || m_interpretation->getTypenumber() == 1 || m_interpretation->getTypenumber() == 8){
       intensity = 0;
       factors = tmp_mask * m_intensity_global_actual;
     }
   }
   if(!skip){
     m_mother->add_to_values_abs(-influence);
     m_mother->add_to_values_fac(-factors);
     m_mother->add_to_uni_fac(-intensity);
   }
 }
upload_influence()
void Segment::upload_influence ()
Definition at line 122 of file segment.cpp.
References m_hasMask_actual, m_id, m_intensity_global_actual, m_intensity_local_actual, m_interpretation, m_mask, m_mother, m_uni_fac, m_values_abs, m_values_fac, normalize_factor(), and updateMask().
Referenced by interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), update_intensity(), and work().
{
 //  std::cout<<"upload\n";
   // should be muted from above
   // intensity could be uplaoded here
   float intensity = -1;
   bool skip = false;
   cv::Mat factors = m_values_fac.clone();
   cv::Mat influence = m_values_abs.clone();
   if(m_interpretation->get_upload_specification() == 0){
     if(m_uni_fac != 0)
       influence = (m_values_abs * ((float) 1 / ((float) m_uni_fac))) * m_intensity_local_actual * m_intensity_global_actual;
     else
       skip = true;
     intensity = m_intensity_global_actual;
   }
   else if(m_interpretation->get_upload_specification() == 1){
     normalize_factor(influence, factors);
     influence = influence * m_intensity_local_actual * m_intensity_global_actual;
     factors = factors * m_intensity_global_actual;
     intensity = m_uni_fac;
   }
   else{
     std::cout<< "upload influence is not allowed yet " << m_interpretation->getTypenumber() << "\n";
   }
   if(m_hasMask_actual){
     std::cout<<"XXXXXXXXXXread mask for upload\n";
     updateMask("mask" + std::to_string(m_id) + ".png");
     cv::Mat tmp_mask = cv::Mat(m_mother->get_max_Point().y, m_mother->get_max_Point().x, CV_32FC3, cv::Scalar(0,0,0));
     int from_to[] = { 0,0, 0,1, 0,2};
     cv::mixChannels(&m_mask, 1, &tmp_mask, 1, from_to, 3);
     factors = factors.mul(tmp_mask);
     influence = influence.mul(tmp_mask);
     if( m_interpretation->getTypenumber() == 0 || m_interpretation->getTypenumber() == 1 || m_interpretation->getTypenumber() == 8){
       intensity = 0;
       factors = tmp_mask * m_intensity_global_actual;
     }
   }
   if(!skip){
     m_mother->add_to_values_abs(influence);
     m_mother->add_to_values_fac(factors);
     m_mother->add_to_uni_fac(intensity);
   }
 }
move_in_time()
void Segment::move_in_time (int delta)
Definition at line 780 of file segment.cpp.
References m_frame_last_destin, m_frame_start_destin, m_mutex_soll, and ready_to_work().
{
   m_mutex_soll.lock();
   m_frame_start_destin += delta;
   m_frame_last_destin += delta;
   m_mutex_soll.unlock();
   ready_to_work();
 }
set_exposure()
void Segment::set_exposure (int new_exposure)
Definition at line 789 of file segment.cpp.
References m_frame_last_destin, m_frame_start_destin, m_mutex_soll, and ready_to_work().
{
   m_mutex_soll.lock();
   m_frame_last_destin = m_frame_start_destin + new_exposure;
   m_mutex_soll.unlock();
   ready_to_work();
 }
set_startframe()
void Segment::set_startframe (int imgs)
Definition at line 797 of file segment.cpp.
References m_frame_start_destin, m_mutex_soll, and ready_to_work().
{
   m_mutex_soll.lock();
   m_frame_start_destin = imgs;
   m_mutex_soll.unlock();
   ready_to_work();
 }
set_endframe()
void Segment::set_endframe (int imgs)
Definition at line 805 of file segment.cpp.
References m_frame_last_destin, m_mutex_soll, and ready_to_work().
{
   m_mutex_soll.lock();
   m_frame_last_destin = imgs;
   m_mutex_soll.unlock();
   ready_to_work();
 }
set_exposure_delta()
void Segment::set_exposure_delta (int delta)
Definition at line 813 of file segment.cpp.
References m_frame_last_destin, m_mutex_soll, and ready_to_work().
{
   m_mutex_soll.lock();
   m_frame_last_destin += delta;
   m_mutex_soll.unlock();
   ready_to_work();
 }
set_local_intensity()
void Segment::set_local_intensity (float i)
Definition at line 821 of file segment.cpp.
References m_intensity_local_destin, m_mutex_soll, and ready_to_work().
{
   m_mutex_soll.lock();
   m_intensity_local_destin = i;
   m_mutex_soll.unlock();
   ready_to_work();
 }
set_global_intensity()
void Segment::set_global_intensity (float i)
Definition at line 829 of file segment.cpp.
References m_intensity_global_destin, m_mutex_soll, and ready_to_work().
{
   m_mutex_soll.lock();
   m_intensity_global_destin = i;
   m_mutex_soll.unlock();
   ready_to_work();
 }
manipulate()
void Segment::manipulate (int start, int end, float local_i, float global_i, bool hasMask)
Definition at line 837 of file segment.cpp.
References m_frame_last_destin, m_frame_start_destin, m_hasMask_destin, m_intensity_global_destin, m_intensity_local_destin, m_interpretation, m_mutex_soll, m_mutex_state, m_needs_reset, m_percent, and ready_to_work().
{
   end += 1;//including the end frame to calculation
   m_mutex_soll.lock();
   m_frame_start_destin = start;
   if(m_frame_last_destin != end && m_interpretation->get_calculation_specification() == 2){
     m_needs_reset = true;
   }
   m_frame_last_destin = end;
   m_intensity_local_destin = local_i;
   m_intensity_global_destin = global_i;
   m_hasMask_destin = hasMask;
   m_mutex_soll.unlock();
   m_mutex_state.lock();
   m_percent = 0;
   m_mutex_state.unlock();
   ready_to_work();
 }
set_interpretation()
void Segment::set_interpretation (std::shared_ptr< Interpretation > interpret)
Definition at line 267 of file segment.cpp.
References m_interpretation, m_mutex_soll, m_new_interpretation, and ready_to_work().
{
   if(m_interpretation->get_id() == interpret->get_id()) {
     std::cout << "the just set interpretation is already set. \n";
   }
   else {
     m_mutex_soll.lock();
     m_new_interpretation = interpret;
     m_mutex_soll.unlock();
     std::cout << "\t > recalculating Segment\n";
     ready_to_work();
   }
 }
update_interpretation()
void Segment::update_interpretation ()
Definition at line 289 of file segment.cpp.
References m_mutex_soll, m_needs_reset, and ready_to_work().
{
   //is called, when complete recomput
   m_mutex_soll.lock();
   m_needs_reset = true;
   m_mutex_soll.unlock();
   ready_to_work();
 }
trigger_interpretation()
void Segment::trigger_interpretation ()
Definition at line 298 of file segment.cpp.
References m_mutex_soll, m_needs_soft_reset, and ready_to_work().
{
   //is called, when complete recomput
   m_mutex_soll.lock();
   m_needs_soft_reset = true;
   m_mutex_soll.unlock();
   ready_to_work();
 }
delete_seg()
void Segment::delete_seg ()
Definition at line 855 of file segment.cpp.
References m_intensity_global_destin, m_mutex_soll, and ready_to_work().
{
   m_mutex_soll.lock();
   m_intensity_global_destin=0;
   m_mutex_soll.unlock();
   ready_to_work();
 }
reset()
void Segment::reset ()
Definition at line 57 of file segment.cpp.
References m_frame_last_actual, m_frame_start_actual, m_mother, m_percent, m_uni_fac, m_values_abs, and m_values_fac.
Referenced by interpret_extending(), interpret_free(), interpret_one_way(), and work().
                    {
 //  std::cout << "\t > reset segment. \n";
   m_frame_start_actual = -1;
   m_frame_last_actual = -1;
   m_values_abs = cv::Mat(m_mother->get_height(), m_mother->get_width(), m_mother->get_img_type(), cv::Scalar(0,0,0));
   m_values_fac = cv::Mat(m_mother->get_height(), m_mother->get_width(), m_mother->get_img_type(), cv::Scalar(0,0,0));
   m_uni_fac = 0;
   m_percent= 0;
 }
soft_reset()
void Segment::soft_reset ()
Definition at line 67 of file segment.cpp.
References m_frame_last_actual, m_frame_start_actual, and m_percent.
Referenced by interpret_directed(), and work().
{
   //std::cout << "\t > reset segment. \n";
   m_frame_start_actual = 0;
   m_frame_last_actual = 0;
   //m_uni_fac = 0;
   m_percent= 0;
 }
get_progress()
float Segment::get_progress ()
Definition at line 282 of file segment.cpp.
References m_mutex_state, and m_percent.
{
   m_mutex_state.lock();
   float out = m_percent;
   m_mutex_state.unlock();
   return out;
 }
get_start()
int Segment::get_start ()
Definition at line 863 of file segment.cpp.
References m_frame_start_destin, and m_mutex_soll.
                       {
   m_mutex_soll.lock();
   int start = m_frame_start_destin;
   m_mutex_soll.unlock();
   return start;
 }
get_end()
int Segment::get_end ()
Definition at line 870 of file segment.cpp.
References m_frame_last_destin, and m_mutex_soll.
                     {
   m_mutex_soll.lock();
   int end = m_frame_last_destin;
   m_mutex_soll.unlock();
   return end;
 }
ready_to_work()
void Segment::ready_to_work () private
Definition at line 44 of file segment.cpp.
References m_mother, m_mutex_state, and m_work_done.
Referenced by delete_seg(), manipulate(), move_in_time(), Segment(), set_endframe(), set_exposure(), set_exposure_delta(), set_global_intensity(), set_interpretation(), set_local_intensity(), set_startframe(), trigger_interpretation(), and update_interpretation().
{
   m_mutex_state.lock();
   bool state = m_work_done;
   m_mutex_state.unlock();
   if(state) {
     m_mutex_state.lock();
     m_work_done = false;
     m_mutex_state.unlock();
     m_mother->add_work(this);
   }
 }
save_segment_out()
void Segment::save_segment_out () private
Definition at line 766 of file segment.cpp.
References m_id, m_intensity_local_actual, m_uni_fac, m_values_abs, and m_values_fac.
Referenced by work().
{
   auto start_time = std::chrono::high_resolution_clock::now();
   std::string out_file = std::string("out_seg_id") + std::to_string(m_id) + ".png";
   cv::imwrite(out_file, m_values_abs / (m_values_fac + cv::Scalar(m_uni_fac, m_uni_fac, m_uni_fac)) * m_intensity_local_actual);
   auto end_time = std::chrono::high_resolution_clock::now();
   auto duration = std::chrono::duration_cast< std::chrono::milliseconds >( end_time - start_time ).count();
   #ifdef show_time
       std::cout << "\t\t * Segment_save_time: \t" << duration << std::endl;
   #endif
 }
normalize_factor()
void Segment::normalize_factor (cv::Mat & influence, cv::Mat & factors) private
Definition at line 172 of file segment.cpp.
Referenced by revert_influence(), and upload_influence().
{
   influence = influence / factors;
   factors = factors / factors;
 }
Member Data Documentation
m_id
int Segment::m_id private
Definition at line 76 of file segment.hpp.
Referenced by interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), save_segment_out(), Segment(), upload_influence(), and work().
m_percent
float Segment::m_percent private
Definition at line 77 of file segment.hpp.
Referenced by get_progress(), manipulate(), reset(), Segment(), soft_reset(), and work().
m_work_done
bool Segment::m_work_done private
Definition at line 78 of file segment.hpp.
Referenced by ready_to_work(), Segment(), and work().
m_hasMask_destin
bool Segment::m_hasMask_destin private
Definition at line 79 of file segment.hpp.
Referenced by manipulate(), Segment(), and work().
m_hasMask_actual
bool Segment::m_hasMask_actual private
Definition at line 80 of file segment.hpp.
Referenced by revert_influence(), Segment(), updateMask(), upload_influence(), and work().
m_frame_start_destin
int Segment::m_frame_start_destin private
Definition at line 83 of file segment.hpp.
Referenced by get_start(), interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), manipulate(), move_in_time(), Segment(), set_exposure(), set_startframe(), and work().
m_frame_last_destin
int Segment::m_frame_last_destin private
Definition at line 84 of file segment.hpp.
Referenced by get_end(), interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), manipulate(), move_in_time(), Segment(), set_endframe(), set_exposure(), set_exposure_delta(), and work().
m_frame_start_actual
int Segment::m_frame_start_actual private
Definition at line 85 of file segment.hpp.
Referenced by interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), reset(), Segment(), soft_reset(), and work().
m_frame_last_actual
int Segment::m_frame_last_actual private
Definition at line 86 of file segment.hpp.
Referenced by interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), reset(), Segment(), soft_reset(), and work().
m_intensity_local_destin
float Segment::m_intensity_local_destin private
Definition at line 88 of file segment.hpp.
Referenced by manipulate(), Segment(), set_local_intensity(), and update_intensity().
m_intensity_global_destin
float Segment::m_intensity_global_destin private
Definition at line 89 of file segment.hpp.
Referenced by delete_seg(), manipulate(), Segment(), set_global_intensity(), and update_intensity().
m_intensity_local_actual
float Segment::m_intensity_local_actual private
Definition at line 90 of file segment.hpp.
Referenced by revert_influence(), save_segment_out(), Segment(), update_intensity(), and upload_influence().
m_intensity_global_actual
float Segment::m_intensity_global_actual private
Definition at line 91 of file segment.hpp.
Referenced by revert_influence(), Segment(), update_intensity(), and upload_influence().
m_interpretation
std::shared_ptr<Interpretation> Segment::m_interpretation private
Definition at line 93 of file segment.hpp.
Referenced by interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), manipulate(), revert_influence(), Segment(), set_interpretation(), upload_influence(), and work().
m_new_interpretation
std::shared_ptr<Interpretation> Segment::m_new_interpretation private
Definition at line 94 of file segment.hpp.
Referenced by Segment(), set_interpretation(), and work().
m_values_abs
cv::Mat Segment::m_values_abs private
Definition at line 97 of file segment.hpp.
Referenced by interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), reset(), revert_influence(), save_segment_out(), Segment(), and upload_influence().
m_values_fac
cv::Mat Segment::m_values_fac private
Definition at line 98 of file segment.hpp.
Referenced by interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), reset(), revert_influence(), save_segment_out(), Segment(), and upload_influence().
m_mask
cv::Mat Segment::m_mask private
Definition at line 99 of file segment.hpp.
Referenced by revert_influence(), Segment(), updateMask(), and upload_influence().
m_uni_fac
float Segment::m_uni_fac private
Definition at line 100 of file segment.hpp.
Referenced by interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), reset(), revert_influence(), save_segment_out(), Segment(), and upload_influence().
m_mother
std::shared_ptr<Base> Segment::m_mother private
Definition at line 103 of file segment.hpp.
Referenced by ready_to_work(), reset(), revert_influence(), updateMask(), and upload_influence().
m_mutex_soll
std::mutex Segment::m_mutex_soll private
Definition at line 106 of file segment.hpp.
Referenced by delete_seg(), get_end(), get_start(), interpret_directed(), interpret_extending(), interpret_free(), interpret_one_way(), manipulate(), move_in_time(), Segment(), set_endframe(), set_exposure(), set_exposure_delta(), set_global_intensity(), set_interpretation(), set_local_intensity(), set_startframe(), trigger_interpretation(), update_intensity(), update_interpretation(), and work().
m_mutex_state
std::mutex Segment::m_mutex_state private
Definition at line 107 of file segment.hpp.
Referenced by get_progress(), manipulate(), ready_to_work(), Segment(), and work().
m_needs_reset
bool Segment::m_needs_reset private
Definition at line 108 of file segment.hpp.
Referenced by manipulate(), Segment(), update_interpretation(), and work().
m_needs_soft_reset
bool Segment::m_needs_soft_reset private
Definition at line 109 of file segment.hpp.
Referenced by Segment(), trigger_interpretation(), and work().
The documentation for this class was generated from the following files:
backend/TBPsys/include/segment.hpp
backend/TBPsys/src/segment.cpp