TimeBasedPictures: Boost Class Reference
Boost Class Reference
#include <boost.hpp>
Public Member Functions
Boost (std::shared_ptr< Base > mother, int id, cv::Mat ref, float threshhold, int modi, int offset, int stride)
~Boost () override
int getTypenumber () override
int get_calculation_specification () override
void calc (int id, int start, int length, int sign, cv::Mat &result, float &factor, cv::Mat &fac_mat) override
void compute_frame (cv::Mat &result, cv::Mat &fac_mat, cv::Mat &current_frame, int sign)
void manipulate (cv::Mat ref_frame, float threshhold, int modi, int offset, int stride)
Public Member Functions inherited from Interpretation
Interpretation (std::shared_ptr< Base > mother, int id, int offset, int stride)
int get_id ()
int get_offset ()
int get_stride ()
virtual ~Interpretation ()
int get_upload_specification ()
virtual void add_connection (int id, Segment *segment)
void delete_connection (int id)
void update_connections ()
void trigger_connections ()
Private Attributes
float m_threshhold
int m_modi
int m_ptr_delta
cv::Point m_pnt_min
cv::Point m_pnt_max
cv::Mat m_reference
Additional Inherited Members
Protected Attributes inherited from Interpretation
int m_offset
int m_stride
std::shared_ptr< cv::VideoCapture > m_video
int m_img_type
int m_id
int m_type
int m_upload_specification
int m_calc_specification
bool m_recompute = false
std::mutex m_mutex_connections
std::shared_ptr< Base > m_base
std::map< int, Segment *> m_all_connections = std::map< int, Segment* >()
Detailed Description
Definition at line 11 of file boost.hpp.
Constructor & Destructor Documentation
Boost()
Boost::Boost (std::shared_ptr< Base > mother, int id, cv::Mat ref, float threshhold, int modi, int offset, int stride)
Definition at line 13 of file boost.cpp.
References Interpretation::m_calc_specification, m_modi, m_pnt_max, m_pnt_min, m_ptr_delta, m_reference, m_threshhold, Interpretation::m_type, and Interpretation::m_upload_specification.
                                                                                                               :
 Interpretation{ mother, id, offset, stride},
 m_reference{ref},
 m_threshhold{threshhold},
 m_modi{modi},
 m_ptr_delta{mother->get_img_delta()},
 m_pnt_min{mother->get_min_Point()},
 m_pnt_max{mother->get_max_Point()}
 {
   m_type                  = 3;  //boost
   m_calc_specification    = 0;  //free
   m_upload_specification  = 1;  //with fac mat
 }
~Boost()
Boost::~Boost () override
Definition at line 27 of file boost.cpp.
              {
   //std::cout<<"deleting interpretation-boost\n";
 }
Member Function Documentation
getTypenumber()
int Boost::getTypenumber () override virtual
Implements Interpretation.
Definition at line 31 of file boost.cpp.
References Interpretation::m_type.
{
   return m_type;
 }
get_calculation_specification()
int Boost::get_calculation_specification () override virtual
Implements Interpretation.
Definition at line 35 of file boost.cpp.
References Interpretation::m_calc_specification.
{
   return m_calc_specification;  //standard sum-game
 }
calc()
void Boost::calc (int id, int start, int length, int sign, cv::Mat & result, float & factor, cv::Mat & fac_mat) override virtual
Implements Interpretation.
Definition at line 39 of file boost.cpp.
References compute_frame(), Interpretation::m_img_type, Interpretation::m_offset, Interpretation::m_stride, and Interpretation::m_video.
{
   auto start_time = std::chrono::high_resolution_clock::now();
   cv::Mat tmp_frame;
   m_video->set( CV_CAP_PROP_POS_MSEC, start/*frameTime*/);
   for(int i = 0; i < length; i++){
     if(start + i < m_offset || (start - m_offset + i) % (m_stride + 1) != 0 ){
       m_video->grab();
     }
     else{
       m_video->read(tmp_frame);
       if(tmp_frame.empty()){
         std::cout << "frame not loaded. \n";
       }
       tmp_frame.convertTo(tmp_frame, m_img_type);   //do this for the whole video right at the start!?
       compute_frame(result, fac_mat, tmp_frame, sign);
     }
     auto end_time = std::chrono::high_resolution_clock::now();
     auto duration = std::chrono::duration_cast< std::chrono::milliseconds >( end_time - start_time ).count();
     #ifdef show_time
         std::cout << "\t\t + Boost ("<<length<<") time: \t" << duration << std::endl;
     #endif
   }
 }
compute_frame()
void Boost::compute_frame (cv::Mat & result, cv::Mat & fac_mat, cv::Mat & current_frame, int sign)
Definition at line 66 of file boost.cpp.
References utils::CIE76(), utils::CIE94(), utils::dE2000(), Interpretation::m_base, m_modi, m_pnt_max, m_pnt_min, m_ptr_delta, m_reference, m_threshhold, and utils::rgb2lab().
Referenced by calc().
{
   if(m_modi == 0){
     cv::Mat mask;
     cv::absdiff(current_frame, m_reference, mask);
     mask = (mask > m_threshhold);
     mask.convertTo(mask, CV_32FC3);
     int from_to[] = { 0,0, 0,1, 0,2};
     cv::mixChannels(&mask, 1, &mask, 1, from_to, 3);
     result += current_frame.mul(mask) * (float) ((float)sign / ((float)255));
     fac_mat += mask * (float) ((float)sign / ((float)255));
   }
   else if(m_modi == 1){
     cv::Mat mask;
     cv::Mat grey_ref = m_reference.clone();
     cv::Mat grey_current = current_frame.clone();
     cv::Mat tmp = cv::Mat(m_base->get_height(), m_base->get_width(), m_base->get_img_type(), cv::Scalar(0,0,0));
     cv::cvtColor(current_frame, grey_current, CV_BGR2GRAY);
     cv::cvtColor(m_reference, grey_ref, CV_BGR2GRAY);
     grey_current.convertTo(grey_current, CV_32FC3);
     grey_ref.convertTo(grey_ref, CV_32FC3);
     cv::absdiff(grey_current, grey_ref, mask);
     mask = (mask > m_threshhold);
     mask.convertTo(mask, CV_32FC3);
     int from_to[] = { 0,0, 0,1, 0,2};
     cv::mixChannels(&mask, 1, &tmp, 1, from_to, 3);
     result += current_frame.mul(tmp) * (float) ((float)sign / ((float)255));
     fac_mat += tmp * (float) ((float)sign / ((float)255));
   }
   else if(m_modi == 2 || m_modi == 3 || m_modi == 4){
     for (unsigned int row = m_pnt_min.y; row < m_pnt_max.y; ++row) {
       //ptr:
       float* ptr_res            =  (float*) result.ptr(row);
       float* ptr_fac            =  (float*) fac_mat.ptr(row);
       const float* ptr_ref      =  (float*) m_reference.ptr(row);
       const float* ptr_current  =  (float*) current_frame.ptr(row);
       for (unsigned int col = m_pnt_min.x; col < m_pnt_max.x; col++) {
         //ptr:
         float *uc_pixel_res           = ptr_res;
         float *uc_pixel_fac           = ptr_fac;
         const float *uc_pixel_ref     = ptr_ref;
         const float *uc_pixel_current = ptr_current;
         //current frame != ref frame -> result frame/ result fac
         // float distance_RGB = sqrt(pow(uc_pixel_ref[0] - uc_pixel_current[0], 2) +
         //                           pow(uc_pixel_ref[1] - uc_pixel_current[1], 2) +
         //                           pow(uc_pixel_ref[2] - uc_pixel_current[2], 2));
         float distance_RGB = -1;
         cv::Scalar ref = utils::rgb2lab(uc_pixel_ref[0], uc_pixel_ref[1], uc_pixel_ref[2]);
         cv::Scalar current = utils::rgb2lab(uc_pixel_current[0], uc_pixel_current[1], uc_pixel_current[2]);
         if(m_modi == 2){
           distance_RGB = utils::dE2000(ref, current, 0.1f, 100.0f, 100.0f);
         }
         else if(m_modi == 3){
           distance_RGB = utils::CIE76(ref, current, 1.0f, 0.0f, 0.0f);
         }
         else if(m_modi == 4){
           distance_RGB = utils::CIE94(ref, current, 5.0f, 100.0f, 100.0f);
         }
         if(distance_RGB > m_threshhold){
           if(sign > 0) {
             uc_pixel_res[0] += uc_pixel_current[0];
             uc_pixel_res[1] += uc_pixel_current[1];
             uc_pixel_res[2] += uc_pixel_current[2];
             uc_pixel_fac[0] += 1;
             uc_pixel_fac[1] += 1;
             uc_pixel_fac[2] += 1;
           }
           else {
             uc_pixel_res[0] -= uc_pixel_current[0];
             uc_pixel_res[1] -= uc_pixel_current[1];
             uc_pixel_res[2] -= uc_pixel_current[2];
             uc_pixel_fac[0] -= 1;
             uc_pixel_fac[1] -= 1;
             uc_pixel_fac[2] -= 1;
           }
         }
         //shift ptr:
         ptr_res     += m_ptr_delta;
         ptr_current += m_ptr_delta;
         ptr_ref     += m_ptr_delta;
         ptr_fac     += m_ptr_delta;
       }
     }
   }
 }
manipulate()
void Boost::manipulate (cv::Mat ref_frame, float threshhold, int modi, int offset, int stride)
Definition at line 160 of file boost.cpp.
References m_modi, Interpretation::m_offset, m_reference, Interpretation::m_stride, m_threshhold, and Interpretation::update_connections().
Referenced by Base::manipulate_interpretation().
{
   bool update_status = false;
   cv::Mat tmp;
   double min = 0, max = 0;
   cv::absdiff(m_reference, ref_frame, tmp);
   cv::minMaxLoc(tmp, &min, &max);
   if(max > 0){
     m_reference = ref_frame;
     update_status = true;
   }
   if(m_threshhold != threshhold){
     m_threshhold = threshhold;
     update_status = true;
   }
   if(m_modi != modi){
     m_modi = modi;
     update_status = true;
   }
   if(offset != m_offset){
     m_offset = offset;
     update_status = true;
   }
   if(stride != m_stride){
     m_stride = stride;
     update_status = true;
   }
   if(update_status){
     update_connections();
   }
 }
Member Data Documentation
m_threshhold
float Boost::m_threshhold private
Definition at line 22 of file boost.hpp.
Referenced by Boost(), compute_frame(), and manipulate().
m_modi
int Boost::m_modi private
Definition at line 23 of file boost.hpp.
Referenced by Boost(), compute_frame(), and manipulate().
m_ptr_delta
int Boost::m_ptr_delta private
Definition at line 24 of file boost.hpp.
Referenced by Boost(), and compute_frame().
m_pnt_min
cv::Point Boost::m_pnt_min private
Definition at line 25 of file boost.hpp.
Referenced by Boost(), and compute_frame().
m_pnt_max
cv::Point Boost::m_pnt_max private
Definition at line 26 of file boost.hpp.
Referenced by Boost(), and compute_frame().
m_reference
cv::Mat Boost::m_reference private
Definition at line 27 of file boost.hpp.
Referenced by Boost(), compute_frame(), and manipulate().
The documentation for this class was generated from the following files:
backend/TBPsys/include/boost.hpp
backend/TBPsys/src/boost.cpp