TimeBasedPictures: utils Namespace Reference
utils Namespace Reference
Functions
float dE2000 (cv::Scalar color1, cv::Scalar color2, float kl, float kc, float kh)
float CIE76 (cv::Scalar color1, cv::Scalar color2, float kl, float kc, float kh)
float CIE94 (cv::Scalar color1, cv::Scalar color2, float kl, float kc, float kh)
cv::Scalar rgb2lab (float r, float g, float b)
float sigmoid (float x, float exponent, float mid)
std::shared_ptr< std::vector< float > > pointsToWeights (std::shared_ptr< std::vector< float >> points, int length)
std::shared_ptr< std::vector< float > > pointsToWeightsIntegral (std::shared_ptr< std::vector< float >> points, int length)
Function Documentation
dE2000()
float utils::dE2000 (cv::Scalar color1, cv::Scalar color2, float kl, float kc, float kh)
Definition at line 9 of file utils.cpp.
Referenced by BoostColor::compute_frame(), Reduce::compute_frame(), Overplott::compute_frame(), and Boost::compute_frame().
CIE76()
float utils::CIE76 (cv::Scalar color1, cv::Scalar color2, float kl, float kc, float kh)
Definition at line 103 of file utils.cpp.
Referenced by BoostColor::compute_frame(), Reduce::compute_frame(), Overplott::compute_frame(), and Boost::compute_frame().
CIE94()
float utils::CIE94 (cv::Scalar color1, cv::Scalar color2, float kl, float kc, float kh)
Definition at line 107 of file utils.cpp.
Referenced by BoostColor::compute_frame(), Reduce::compute_frame(), Overplott::compute_frame(), and Boost::compute_frame().
rgb2lab()
cv::Scalar utils::rgb2lab (float r, float g, float b)
Definition at line 121 of file utils.cpp.
Referenced by BoostColor::compute_frame(), Reduce::compute_frame(), Overplott::compute_frame(), and Boost::compute_frame().
sigmoid()
float utils::sigmoid (float x, float exponent, float mid)
Definition at line 168 of file utils.cpp.
Referenced by Circularfade::create_time_map(), and Timefadepoints::create_time_map().
pointsToWeights()
std::shared_ptr< std::vector< float > > utils::pointsToWeights (std::shared_ptr< std::vector< float >> points, int length)
Definition at line 172 of file utils.cpp.
pointsToWeightsIntegral()
std::shared_ptr< std::vector< float > > utils::pointsToWeightsIntegral (std::shared_ptr< std::vector< float >> points, int length)
Definition at line 198 of file utils.cpp.
Referenced by Transferfunction::calc().